apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cd-binding
  labels:
    app: promotions
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: branch
      # Strips "refs/heads/" prefix from the GitHub push event ref
      value: $(body.ref)
