apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cd-listener
  labels:
    app: promotions
spec:
  to:
    kind: Service
    name: el-cd-listener
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
