apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cd-binding
  labels:
    app: promotions
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: branch
      value: $(extensions.branch_name)
